---
- name: Add repository
  yum_repository:
    name: yarn
    description: yarn repo
    baseurl: "{{ yarn_rhel_repo_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ yarn_rhel_repo_gpg_key_url }}"
    state: present

- name: Install Yarn
  package:
    name: yarn
    state: latest