---
- hosts: all

  roles:
    - { role: common,                                tags: [ "common" ] }
    - { role: geerlingguy.repo-remi,                 tags: [ "php" ] }
    - { role: geerlingguy.git,                       tags: [ "git" ] }    
    - { role: geerlingguy.apache,                    tags: [ "apache" ] }
    - { role: geerlingguy.apache-php-fpm,            tags: [ "apache" ] }
    - { role: geerlingguy.php-versions,              tags: [ "php" ] }
    - { role: geerlingguy.php,                       tags: [ "php" ] }
    - { role: geerlingguy.php-pecl,                  tags: [ "php-pecl" ] }
    - { role: geerlingguy.mysql,                     tags: [ "mysql" ] }
    - { role: geerlingguy.php-mysql,                 tags: [ "mysql" ] }
    - { role: geerlingguy.postgresql,                tags: [ "postgresql" ] }
    - { role: geerlingguy.php-pgsql,                 tags: [ "postgresql" ] }
    - { role: geerlingguy.composer,                  tags: [ "php" ] }
